import {api,authStore} from "./api.js";
import {authStorage} from "./auth-storage.js";
const $=id=>document.getElementById(id);let month=new Date().toISOString().slice(0,7),clientId="";
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char]));
const showLogin=message=>{$("workspace-view").hidden=true;$("network-view").hidden=true;$("login-view").hidden=false;$("login-error").textContent=message||""};
const showNetwork=()=>{$("login-view").hidden=true;$("workspace-view").hidden=true;$("network-view").hidden=false};
function monthLabel(value){return new Intl.DateTimeFormat("fr-FR",{month:"long",year:"numeric"}).format(new Date(`${value}-01T12:00:00`))}
async function loadCalendar(){try{$("workspace-status").textContent="Chargement du calendrier...";const {calendar}=await api.getCalendar(month,clientId);$("month-label").textContent=monthLabel(calendar.month);$("month-summary").textContent=`${calendar.totalHHMM} travaillées · ${calendar.totalOvertimeHHMM} supplémentaires`;$("calendar-days").innerHTML=calendar.entries.length?calendar.entries.map(entry=>`<article><strong>${entry.work_date_display}</strong><span>${entry.worked_hhmm||"—"} · ${entry.day_type_display}</span></article>`).join(""):"<p>Aucune journée pour cette période.</p>";$("workspace-status").textContent=""}catch(error){if(error.message==="UNAUTHENTICATED")showLogin("Session expirée.");else $("workspace-status").textContent="Calendrier indisponible."}}
async function start(){try{const me=await api.getMe(),clients=await api.getClients();$("user-name").textContent=me.user.username;$("client-select").innerHTML=clients.clients.map(c=>`<option value="${Number(c.id)}">${escapeHtml(c.companyName)}</option>`).join("");clientId=$("client-select").value;if(!clientId)throw new Error("NO_CLIENT");$("login-view").hidden=true;$("network-view").hidden=true;$("workspace-view").hidden=false;await loadCalendar()}catch(error){if(error.message==="UNAUTHENTICATED")showLogin("Session expirée.");else if(["TIMEOUT","NETWORK_ERROR","SERVER_ERROR"].includes(error.message))showNetwork();else showLogin("Impossible de charger votre espace.")}}
$("login-form").addEventListener("submit",async event=>{event.preventDefault();const data=new FormData(event.currentTarget);$("login-submit").disabled=true;$("login-submit").textContent="Connexion...";let result;try{result=await api.login(data.get("username"),data.get("password"))}catch{showLogin("Identifiant ou mot de passe invalide.");$("login-submit").disabled=false;$("login-submit").textContent="Connexion";return}try{await authStorage.setToken(result.token)}catch{try{await authStorage.removeToken()}catch{}showLogin("Connexion réussie, mais la session n'a pas pu être enregistrée sur cet appareil.");$("login-submit").disabled=false;$("login-submit").textContent="Connexion";return}await start();$("login-submit").disabled=false;$("login-submit").textContent="Connexion"});$("client-select").addEventListener("change",event=>{clientId=event.target.value;loadCalendar()});$("previous-month").onclick=()=>{month=new Date(`${month}-01T12:00:00`);month.setMonth(month.getMonth()-1);month=month.toISOString().slice(0,7);loadCalendar()};$("next-month").onclick=()=>{month=new Date(`${month}-01T12:00:00`);month.setMonth(month.getMonth()+1);month=month.toISOString().slice(0,7);loadCalendar()};$("logout-button").onclick=async()=>{try{await api.logout()}catch{}await authStorage.removeToken();showLogin()};
$("retry-button").onclick=()=>start();
authStorage.getToken().then(token=>token?start():showLogin());
